### ISSUE TITLE
Vehicle GetPosition Method not Working.

### ISSUE THREAD

**Issue by Sommy1491** [CodingConnected/CodingConnected.Traci#1]
Hi,
While trying Vehicle.GetPosition() Method, It return "System.ArgumentOutOfRangeException".
I Debug the "TraCIDataConverter Class" and found this method returning "type" 0x01 as Response.
I think it should actual return First 0x0F because this method is of compound type and then 0x01 as for  Position2D.

**Comment by mennowo** [comment]
Hi @Sommy1491, 
nice to hear someone is using the lib!
At the moment, it is still a work in progress, meaning some elements are lacking. I added all TraCI "get" methods a little while ago, but the implementation cannot yet deal with "compound types". I had no time yet to implement this.
Feel free to submit a pull request, if you get a chance to expand the functionality of the lib. It will probably take me a while to do this myself, I hope to find some time somewhere in March of April this year.
Greets, Menno

**Comment by galfaroth** [comment]
I have the same issue - could you post the solution?

**Comment by mennowo** [comment]
Hello galfaroth,
currently I am unable to implement this due to lack of time. If you manage to implement this, please submit a pull request, so we can extend API coverage of the library.
Thanks, greets, Menno

**Comment by FlorianJa** [comment]
should be fixed by #6
