### ISSUE TITLE
HandleResponse doesn't support Context Subscription.

### ISSUE THREAD

**Issue by cchadj01** [CodingConnected/CodingConnected.Traci#14]
Hello,
 I am currently adding functionality for context subscription and I am having problem making HandleResponse handle both Context and Variable Subscription. In particular I don't understand this piece of code

                    trresult.Identifier = response[i + j++];

                    if (trresult.Identifier == TraCIConstants.CMD_SIMSTEP && totlength == response.Count() && len + 8 != response.Count())
                    {
                        var revSubCount = response.Skip(i + len).Take(4).Reverse().ToArray();
                        var subCount = BitConverter.ToInt32(revSubCount, 0);
                        len += 5;
                        for (int n = 0; n < subCount; n++)
                        {
                            var revSubResponseLength = response.Skip(i + len).Take(4).Reverse().ToArray();
                            var SubResponseLength = BitConverter.ToInt32(revSubResponseLength, 0);
                            len += SubResponseLength;

                        }

                        trresult.Length = --len;
                    }

What is len in this context and why do you decrement by one at the end?

I have implemented Context Subscription and it works when changing the above code but I can't support both Context and Variable Subscription.

Any input on how HandleResponse code works would be very helpful.

Thank you,
Tom

P.S I didn't know how I could contact you otherwise.
* I have made the context subscription following the pattern for the variable subscription (using events). Is there any important guidelines I must follow so I can push my code?

**Comment by FlorianJa** [comment]
To be honest, after a deeper look at the code you mentioned, i dont rememberwhy i added that. the TraCiResult.Length is only used to detect if the the response to a SimStep has subscriptions attached (https://github.com/CodingConnected/CodingConnected.Traci/blob/master/CodingConnected.TraCI.NET/Helpers/TraCIDataConverter.cs#L22)

please create a pullrequest so i can see your code

**Comment by cchadj01** [comment]
Hello,
 I have made a pull request. It is not functioning and it can only support one Context subscription and can not support variable subscription. (Changing trresult.Length = --len; to trresult.Length = len -1; does that). It is just for demonstration purposes. You can also check the new Variable Subscription System I made (change to trresult.Length = --len). 
 I have also added a demo project so you can test the subscriptions (and for new users to learn how to use the library).

I would really love it if you could solve the problem with HandleRequest so it can support both context and variable subscriptions.
Thank you,
Chrysostomos Chadjiminas.
