### ISSUE TITLE
Step answers with Error on command 0xD4

### ISSUE THREAD

**Issue by T-1200** [CodingConnected/CodingConnected.Traci#2]
Hi!
Much appreciate your work on the C# implementation of the interface.

I've recently tried to extend the TraCI.NET lib on subscription but kinda got stuck now.
My goal is to use TraCI# directly within Unity3D to retrieve data from SUMO and manipulate vehicle-movement in Unity.

I forked the repo and created a branch "clean-up". TraCI.NET's readme shows which scripts are modified or extended. Please excuse my amateurish approach - hope there is something to take from.
The readme also shows how I retrieve the data.

With this approach and sumo run with ```--verbose``` I get an error after invoking the subscription:
```Step #0.20Error: Answered with error to command 0xd4: Wrong position in requestMessage after dispatching command. Expected command length was 21 but 16 Bytes were read.```

Response-array's variable is D4 (but should be E4) and response-byte-array is:
```FF-00-00-00-72-57-72-6F-6E-67-20-70-6F-73-69-74-69-6F-6E-20-69-6E-20-72-65-71-75-65-73-74-4D-65-73-73-61-67-65-20-61-66-74-65-72-20-64-69-73-70-61-74-63-68-69-6E-67-20-63-6F-6D-6D-61-6E-64-2E-20-45-78-70-65-63-74-65-64-20-63-6F-6D-6D-61-6E-64-20-6C-65-6E-67-74-68-20-77-61-73-20-32-31-20-62-75-74-20-31-36-20-42-79-74-65-73-20-77-65-72-65-20-72-65-61-64-2E```

With given information and pseudo-script in the above mentioned branch, it should be possible to reproduce the error. Maybe someone has an idea.

**Comment by mennowo** [comment]
Hi T-1200,
the error SUMO gives after invoking the inscription should give an indication as to where you can start looking for the cause of the problem. It seems the message sent is not exactly correct. I have as of yet never worked with subscriptions, so I cannot really be of help right now.
Try to find out what is wrong with the message that is being sent. Note that to implement subscriptions, you'd also have to implement a way to handle messages that SUMO will start sending after a subscription is successful.
If in doubt, use the SUMO-dev mailing list to get help.
If you manage to get it to work, would be very nice if you can do a pull request so we can extend the API coverage of the lib.
Thanks! 
Menno

**Comment by FlorianJa** [comment]
I worked on subscriptions recently and i will create a new branch and push my work there (maybe still this week).

**Comment by mennowo** [comment]
Hey @FlorianJa, that's great! Let me know if you need any feedback or want to discuss something. Over the next few weeks I have more time, so I can also look at the lib again. There is an upcoming 1.0 release for SUMO, that has some changes for TraCI as well. I will try to look into that beginning of next week, it would be nice to anticipate this.

**Comment by FlorianJa** [comment]
i pushed my work into a new branch (https://github.com/CodingConnected/CodingConnected.Traci/tree/dev_subscriptions)
Subscriptions should work but more testing would be nice, e.g. whats happening if the answer is larger then 2^15 bits (acutal hardcoded buffer size)

**Comment by FlorianJa** [comment]
i will probably work on this from monday, 10.09.

**Comment by FlorianJa** [comment]
Subscriptions should work now.
