### ISSUE TITLE
Error or missunderstanding how to subscribe for vehicles

### ISSUE THREAD

**Issue by KamikyIT** [CodingConnected/CodingConnected.Traci#21]
Hello, I'm using your project for visualizing and real time controlling SUMO simulation.
ASP server for controlling simulation(change trafficlights, summone some vehicles and so on) with Unity3D client.
Behind the scene, I'm starting sumo with project with given ip and port.
C:\Program Files (x86)\Eclipse\Sumo\bin\sumo
-c net_bel.sumocfg 
--step-length 0.2 
--additional-files // some xml files here.
--remote-port 4321

Every 0.2 seconds (same as step length) calling MakeStep.
```
List<string> _vehicleIds = new List<string>();
float _stepLength = 0.2f;
void Start()
    {
        _client = new TraCIClient();

        _client.TrafficLightSubscription += Client_TrafficLightSubscription;
        _client.VehicleContextSubscription += Client_VehicleContextSubscription;
        var res = _client.Connect("localhost", 4321);

        // That's just for tests. The forsing sumo to make a step is called outside at ASP server.
        InvokeRepeating("MakeSumoStep", 1f, _stepLength);
    }
    void MakeSumoStep()
    {
        _client.Control.SimStep();

        _simulationStep += _stepLengthDecimal;

        var activeIds = _client.Vehicle.GetIdList().Content;
        var newIds = activeIds.Where(id => !_vehicleIds.Contains(id)).ToList();
        var removeIds = _vehicleIds.Where(id => !activeIds.Contains(id)).ToList();

        _vehicleIds.AddRange(newIds);

        foreach (var id in newIds)
            _client.Vehicle.SubscribeContext(id, 0, 1000, TraCIConstants.CMD_GET_VEHICLE_VARIABLE, 1000f, vehicleVariablesToSubscribeTo);

        foreach (var id in removeIds)
            _client.Vehicle.UnsubscribeContext(id, TraCIConstants.CMD_GET_VEHICLE_VARIABLE);
    }

    void Client_VehicleContextSubscription(object sender, ContextSubscriptionEventArgs e)
    {
        var simStep = _simulationStep;

        foreach (var item in e.VariableSubscriptionByObjectId)
        {
            var id = item.Value.ObjectId;
            var angle = item.Value.ResponseByVariableCode[TraCIConstants.VAR_ANGLE].GetContentAs<decimal>();
            var position = item.Value.ResponseByVariableCode[TraCIConstants.VAR_POSITION].GetContentAs<Position2D>();
            var lights = item.Value.ResponseByVariableCode[TraCIConstants.VAR_SIGNALS].GetContentAs<int>();
            var type = item.Value.ResponseByVariableCode[TraCIConstants.VAR_TYPE].GetContentAs<string>();

            // Next there're code for visualizing this vehicle at Unity world, but for the text I'll write Debug.Log
            Debug.Log($"{e.ObjectId} {position.X} {position.Y} {_simulationStep}");
        }
    }
```

As you can see, I subscribe to VehicleContextSubscription to handle vehicle's move behvaiour, and caching the _vehicleIds of current active vehicles.
On each forsing SUMO simulation step I subscribe (doing _client.Vehicle.SubscribeContext) to new vehilce IDs and unsubscribe to (doing _client.Vehicle.UnsubscribeContext) to removed vehicle IDs.
But, there's a problem that many vehicle datas are duclicated, so my debug logging is writeing many duplicates. 
For example, "car1_1 0.1 0.1 0.2" was written like 4 times. And this is repeated constantly.

**Comment by mennowo** [comment]
Hello,
it seems somewhat odd to subscribe and unsubscribe continuously. I would propose redesigning, taking a different approach:
- either subscribe _once_ and then monitor the information received - you'll have to study the TraCI protocol in order to make the best use of the subscription system. If you are still having these problems with this approach, it would be great if you could improve upon the current implementation of the subscription model in TraCI.NET and do a PR.
- or, if you prefer manually updating the information each time step - which might prove easier to implement - simply loop all vehicles in the network and retrieve the info you need with the relevant TraCI calls. This approach better fits your current design.
Hope this is helpful.
Greets! Menno

**Comment by FlorianJa** [comment]
For me it seems fine to subscribe to the new vehicles at every step, since you only subscribe to the new ones. You also can use GetDepartedIDList() and GetArrivedIDList() to get the ids of vehicles joining and leaving the network. Probably there is something wrong with the unsubscribe method.

**Comment by mennowo** [comment]
Good point, sorry, I did not look at the code closely enough!

**Comment by FlorianJa** [comment]
@KamikyIT are you sure you want to subscribe to the context?
Please see: https://sumo.dlr.de/docs/TraCI/Object_Context_Subscription.html
https://sumo.dlr.de/docs/TraCI/Object_Variable_Subscription.html

**Comment by KamikyIT** [comment]
@FlorianJa I'm not sure at all. I just want to get notifications about vehicles all over the simulation on every step.

**Comment by FlorianJa** [comment]
well... :D
I guess a normal subscription is what you are looking for.

**Comment by FlorianJa** [comment]
@KamikyIT Please check if the normale subscription works for you or validate the messages from the context subscription. If you have any more problems, describe them in detail here otherwise please close this issuse. Thank you!

**Comment by KamikyIT** [comment]
@FlorianJa 
So now, I'm trying the following.

            ```
var ids = _client.Vehicle.GetIdList();

            foreach (var id in ids.Content)
            {
                var pos = _client.Vehicle.GetPosition(id).Content;
                var type = _client.Vehicle.GetTypeID(id).Content;
                var angle = _client.Vehicle.GetAngle(id).GetContentAs<decimal>();
                var lights = _client.Vehicle.GetSignals(id).Content;

                var vehicle = new Vehicle(id, type)
                {
                    Ang = angle,
                    Lights = lights,
                    X = pos.X,
                    Y = pos.Y,
                    SimulationStep = _simulationStep,
                };
            }
```

**Comment by FlorianJa** [comment]
That’s may work, but the performance is probably very bad. Especially if the amount of vehicle increases. I would suggest working with subscriptions similar as you did before but using "normal" subscription instead of the context subscription.

**Comment by FlorianJa** [comment]
Keep in mind, that every _client.Vehicle.getX is a request to the sumo server. in your case, you have four requests times the amount of vehicle in the network.

**Comment by KamikyIT** [comment]
@FlorianJa Yes, I've tested it. For like 300+ vehicles online it starts lagging.
I'm trying to `_client.Vehicle.Subscribe(id, 0, 3600, vehicleVariablesToSubscribeTo);` and handle each vehicle data from `_client.VehicleSubscription` event. But I cant find method for unsubscribe arrived vehicles(or is it magically unsubscribing behind the scene).

**Comment by FlorianJa** [comment]
You can do something like this to get all subscription responses
`var responses = client.Control.SimStep().Content as List<TraCISubscriptionResponse>;`

Furthermore, subscriptions will end when the simulation passes the third parameter of the Subscribe method (3600 in your case). Actually, I am not sure what’s happening if a vehicle left the simulation before this point.

**Comment by KamikyIT** [comment]
@FlorianJa Looks like exactly what I need! Thank you.
