### ISSUE TITLE
Answered with error to command 0x00

### ISSUE THREAD

**Issue by pariroj** [CodingConnected/CodingConnected.Traci#22]
Hi, I am using OMNeT++-5.5.1, Veins-5.0, and SUMO-1.2.0. I am trying to stop a vehicle at a parking area through **setParkingAreaStop** command, but the simulation terminated with the following error:

**Error: Answered with error to command 0x00: Wrong position in requestMessage after dispatching command 0. Expected command length was 70 but 2 Bytes were read.**

The following is the code of my **setParkingAreaStop** command:

```
void TraCICommandInterface::Vehicle::setParkingAreaStop(std::string edgeId, double endPos, uint8_t laneInd,double duration,uint8_t flag){
    uint8_t variableId = CMD_STOP;
    uint8_t variableType = TYPE_COMPOUND;
    uint8_t Edgetype= TYPE_STRING;
    uint8_t Postype= TYPE_DOUBLE;
    uint8_t Lanetype= TYPE_BYTE;
    uint8_t Durtype= TYPE_INTEGER;
    int32_t count = 5;
    TraCIBuffer buf = connection->query(CMD_SET_VEHICLE_VARIABLE, TraCIBuffer() << variableId << nodeId << variableType << count << Edgetype << edgeId << Postype << endPos << Lanetype << laneInd  << Postype << duration << Lanetype << flag);
        ASSERT(buf.eof());
}
```

How can I solve this problem? please help. Thanks.

**Comment by mennowo** [comment]
Hello, looking at your description and code it seems you are using C++. This repository however, is for a C# implementation of the TraCI protocol. I'd suggesting posting your question [here](https://accounts.eclipse.org/mailing-list/sumo-user).
