### ISSUE TITLE
Vehicle.Remove is not working

### ISSUE THREAD

**Issue by thallkeer** [CodingConnected/CodingConnected.Traci#23]
When i trying to remove any vehicle from the simulation by calling
Vehicle.Remove(vehID, TraCIConstants.REMOVE_VAPORIZED);
Sumo throws an error with message:
Error: Answered with error to command 0xc4: Wrong position in requestMessage after dispatching command 196. Expected command length was 11 but 10 Bytes were read.

Is this a known error or maybe I am doing something wrong?

**Comment by mennowo** [comment]
This is fixed by #25
