### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by FlorianJa** [CodingConnected/CodingConnected.Traci#4]
Something weird happened in this commit https://github.com/CodingConnected/CodingConnected.Traci/commit/ae67cfc2117188968d0f3c70ffa801739a0babc3

the folder  CodingConnected.Traci.NET/CodingConnected.TraCI.NET is now twice there.
one time with CI in TraCI
and one time with ci in Traci

the ci folder does not appear on my pc after fetch & pull.

i want to submit a new pull request and it's telling me that changed each file twice.

**Comment by mennowo** [comment]
Hi @FlorianJa , I've seen that before, no idea how that happens. If you can fix it in the PR, go ahead, I will simply merge it (not squash). If not, I will try to fix it tomorrow.

**Comment by FlorianJa** [comment]
fix by #5
