### ISSUE TITLE
Screenshot - known issues

### ISSUE THREAD

**Issue by FlorianJa** [CodingConnected/CodingConnected.Traci#8]
Gui command "screenshot" does not create screenshot as aspected.
But command returns "success"...

**Comment by mennowo** [comment]
Do we know why the command does not work as expected?

**Comment by FlorianJa** [comment]
I guess it is a problem in Sumo and not directly related to Traci

**Comment by mennowo** [comment]
Then we can close this issue? If the command works but SUMO doesn't, the command still works...

**Comment by FlorianJa** [comment]
I think we can close it.
